{"name":"Dataflow - Get Data from SP","ppdf:dataflowId":"1feb7b72-7eb9-44c9-b9cf-c294b0e4ad2e","ppdf:owner":{"tenantId":"8cc5ffdf-b1ef-4c56-a1b2-908c59b953d0","userId":"957cd1fa-c9f9-4909-8b59-5d8f02400e33"},"ppdf:fastCopy":false,"version":"1.0","culture":"en-US","modifiedTime":"2023-11-07T13:46:51.7730951+00:00","ppdf:outputFileFormat":"Parquet","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"Workspace_users":{"queryId":"f51c454b-4b17-47ce-9c6b-f8d41ae9b258","queryName":"Workspace_users","loadEnabled":true},"DefaultStaging":{"queryId":"f2beae5f-c921-47ee-b647-e13ac44654ad","queryName":"DefaultStaging"},"DestinationForWriteToDatabaseTableFrom_Workspace_users":{"queryId":"a06c94fd-c4db-4e1a-a456-dccab08eafba","queryName":"DestinationForWriteToDatabaseTableFrom_Workspace_users"},"WriteToDatabaseTableFrom_TransformForOutputToDatabaseTableFrom_Workspace_users":{"queryId":"2915765d-2c5e-4ae4-b98a-89de51c173d9","queryName":"WriteToDatabaseTableFrom_TransformForOutputToDatabaseTableFrom_Workspace_users"},"TransformForOutputToDatabaseTableFrom_Workspace_users":{"queryId":"e48c0752-4ba2-4b9f-93f9-62dfb9ff7002","queryName":"TransformForOutputToDatabaseTableFrom_Workspace_users"},"Company_Mapping":{"queryId":"7190bdaf-a03d-4cc6-b925-da5303753cb2","queryName":"Company_Mapping","loadEnabled":true},"DestinationForWriteToDatabaseTableFrom_Company_Mapping":{"queryId":"ff67fd77-8401-4ff1-a374-701eecdee91c","queryName":"DestinationForWriteToDatabaseTableFrom_Company_Mapping"},"WriteToDatabaseTableFrom_TransformForOutputToDatabaseTableFrom_Company_Mapping":{"queryId":"2252ddee-b52f-4c48-ad85-12cf00e585cd","queryName":"WriteToDatabaseTableFrom_TransformForOutputToDatabaseTableFrom_Company_Mapping"},"TransformForOutputToDatabaseTableFrom_Company_Mapping":{"queryId":"a62aefbb-cf1d-4bbe-b0cb-dbb73b97690e","queryName":"TransformForOutputToDatabaseTableFrom_Company_Mapping"},"AD_users":{"queryId":"7e03e31d-0026-4ad4-972e-7342dd240d85","queryName":"AD_users","loadEnabled":true},"DestinationForWriteToDatabaseTableFrom_AD_users":{"queryId":"85374f06-d7ce-46b6-ba5b-129ae0be62e5","queryName":"DestinationForWriteToDatabaseTableFrom_AD_users"},"WriteToDatabaseTableFrom_TransformForOutputToDatabaseTableFrom_AD_users":{"queryId":"07c19ce7-3204-4f84-b61a-0b47e2bed3b8","queryName":"WriteToDatabaseTableFrom_TransformForOutputToDatabaseTableFrom_AD_users"},"TransformForOutputToDatabaseTableFrom_AD_users":{"queryId":"420227d6-180e-453c-b739-7b9942da8812","queryName":"TransformForOutputToDatabaseTableFrom_AD_users"}},"document":"section Section1;\r\n[Staging = \"DefaultStaging\"]\r\nshared Workspace_users = let\n  Source = SharePoint.Files(\"https://pbimlo-my.sharepoint.com/personal/o_manel_pbimlo_onmicrosoft_com/\", [ApiVersion = 15]),\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Folder Path] = \"https://pbimlo-my.sharepoint.com/personal/o_manel_pbimlo_onmicrosoft_com/Documents/AXA GO/Workspaces users/\"),\n  #\"Split column by delimiter\" = Table.SplitColumn(#\"Filtered rows\", \"Name\", Splitter.SplitTextByEachDelimiter({\"_\"}, QuoteStyle.Csv), {\"Name.1\", \"Name.2\"}),\n  #\"Renamed columns\" = Table.RenameColumns(#\"Split column by delimiter\", {{\"Name.1\", \"Name\"}, {\"Name.2\", \"Date\"}}),\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Content\", \"Name\", \"Date\"}),\n  #\"Filtered Rows on Max\" = Table.SelectRows(#\"Removed other columns\", each ([Date] = List.Max(#\"Removed other columns\"[Date]))),\n  Navigation = #\"Filtered Rows on Max\"{0}[Content],\n  #\"Imported CSV\" = Csv.Document(Navigation, [Delimiter = \";\", Columns = 5, Encoding = 65001, QuoteStyle = QuoteStyle.None]),\n  #\"Promoted headers\" = Table.PromoteHeaders(#\"Imported CSV\", [PromoteAllScalars = true])\nin\n  #\"Promoted headers\";\r\nshared DefaultStaging = let\r\n  DefaultStaging = Pipeline.DefaultModelStorage()\r\nin\r\n  DefaultStaging;\r\nshared DestinationForWriteToDatabaseTableFrom_Workspace_users = let\r\n  Pattern = Lakehouse.Contents([]),\r\n  Navigation_1 = Pattern{[workspaceId = \"c724be80-d86a-4027-a5e0-facd68b67834\"]}[Data],\r\n  Navigation_2 = Navigation_1{[lakehouseId = \"c1c439bf-5c3d-4ad4-89a8-2fe31902d3c5\"]}[Data],\r\n  TableNavigation = Navigation_2{[Id = \"Workspace_users\", ItemKind = \"Table\"]}?[Data]?,\r\n  Table = NavigationTable.CreateTableOnDemand(TableNavigation, #table(type table[Workspace = nullable text, WorkspaceID = nullable text, UserPrincipalName = nullable text, AccessRights = nullable text, CompanyName = nullable text], {}), [DeleteWhenEmpty = true])\r\nin\r\n  Table;\r\n[Staging = \"DefaultStaging\"]\r\nshared WriteToDatabaseTableFrom_TransformForOutputToDatabaseTableFrom_Workspace_users = let\r\n  WriteToDatabaseTableFrom_TransformForOutputToDatabaseTableFrom_Workspace_users = Pipeline.ExecuteAction(ValueAction.WithTransaction([Target = DestinationForWriteToDatabaseTableFrom_Workspace_users], (txn) => {TableAction.DeleteRows(txn[Target]), TableAction.InsertRows(txn[Target], TransformForOutputToDatabaseTableFrom_Workspace_users), Action.DoNothing}))\r\nin\r\n  WriteToDatabaseTableFrom_TransformForOutputToDatabaseTableFrom_Workspace_users;\r\nshared TransformForOutputToDatabaseTableFrom_Workspace_users = let\r\n    SourceTable = Table.SelectColumns(Workspace_users, {\"Workspace\", \"WorkspaceID\", \"UserPrincipalName\", \"AccessRights\", \"CompanyName\"})\r\nin\r\n    SourceTable;\r\n[Staging = \"DefaultStaging\"]\r\nshared Company_Mapping = let\n  Source = SharePoint.Files(\"https://pbimlo-my.sharepoint.com/personal/o_manel_pbimlo_onmicrosoft_com/\", [ApiVersion = 15]),\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Folder Path] = \"https://pbimlo-my.sharepoint.com/personal/o_manel_pbimlo_onmicrosoft_com/Documents/AXA GO/\"),\r\n  Navigation = #\"Filtered rows\"{[Name = \"Company_Mapping.xlsx\", #\"Folder Path\" = \"https://pbimlo-my.sharepoint.com/personal/o_manel_pbimlo_onmicrosoft_com/Documents/AXA GO/\"]}[Content],\r\n  #\"Imported Excel workbook\" = Excel.Workbook(Navigation, null, true),\r\n  #\"Navigation 1\" = #\"Imported Excel workbook\"{[Item = \"Company_Mapping_M365\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(#\"Navigation 1\", [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Company\", type text}, {\"OpCo\", type text}, {\"User legal entity code\", type text}}),\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Changed column type\", each ([Company] <> \"(blank)\")),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Filtered rows 1\", {{\"User legal entity code\", \"UserLegalEntityCode\"}})\nin\n  #\"Renamed columns\";\r\nshared DestinationForWriteToDatabaseTableFrom_Company_Mapping = let\r\n  Pattern = Lakehouse.Contents([]),\r\n  Navigation_1 = Pattern{[workspaceId = \"c724be80-d86a-4027-a5e0-facd68b67834\"]}[Data],\r\n  Navigation_2 = Navigation_1{[lakehouseId = \"c1c439bf-5c3d-4ad4-89a8-2fe31902d3c5\"]}[Data],\r\n  TableNavigation = Navigation_2{[Id = \"Company_Mapping\", ItemKind = \"Table\"]}?[Data]?,\r\n  Table = NavigationTable.CreateTableOnDemand(TableNavigation, #table(type table[Company = nullable text, OpCo = nullable text, UserLegalEntityCode = nullable text], {}), [DeleteWhenEmpty = true])\r\nin\r\n  Table;\r\n[Staging = \"DefaultStaging\"]\r\nshared WriteToDatabaseTableFrom_TransformForOutputToDatabaseTableFrom_Company_Mapping = let\r\n  WriteToDatabaseTableFrom_TransformForOutputToDatabaseTableFrom_Company_Mapping = Pipeline.ExecuteAction(ValueAction.WithTransaction([Target = DestinationForWriteToDatabaseTableFrom_Company_Mapping], (txn) => {TableAction.DeleteRows(txn[Target]), TableAction.InsertRows(txn[Target], TransformForOutputToDatabaseTableFrom_Company_Mapping), Action.DoNothing}))\r\nin\r\n  WriteToDatabaseTableFrom_TransformForOutputToDatabaseTableFrom_Company_Mapping;\r\nshared TransformForOutputToDatabaseTableFrom_Company_Mapping = let\r\n    SourceTable = Table.SelectColumns(Company_Mapping, {\"Company\", \"OpCo\", \"UserLegalEntityCode\"})\r\nin\r\n    SourceTable;\r\n[Staging = \"DefaultStaging\"]\r\nshared AD_users = let\n  Source = SharePoint.Files(\"https://pbimlo-my.sharepoint.com/personal/o_manel_pbimlo_onmicrosoft_com/\", [ApiVersion = 15]),\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Folder Path] = \"https://pbimlo-my.sharepoint.com/personal/o_manel_pbimlo_onmicrosoft_com/Documents/AXA GO/\"),\r\n  Navigation = #\"Filtered rows\"{[Name = \"Export_Gad.csv\", #\"Folder Path\" = \"https://pbimlo-my.sharepoint.com/personal/o_manel_pbimlo_onmicrosoft_com/Documents/AXA GO/\"]}[Content],\r\n  #\"Imported CSV\" = Csv.Document(Navigation, [Delimiter = \",\", Columns = 9, Encoding = 1200, QuoteStyle = QuoteStyle.None]),\r\n  #\"Promoted headers\" = Table.PromoteHeaders(#\"Imported CSV\", [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"DN\", type text}, {\"company\", type text}, {\"mail\", type text}, {\"axaAzureSourceAnchor\", type text}, {\"axaCloudProvision\", type logical}, {\"axaDWEnabled\", type logical}, {\"axaAzureLoginUPN\", type text}, {\"axaUserDeletionDate\", type datetime}, {\"info\", type text}}),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Changed column type\", {\"DN\", \"info\"}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Removed columns\", {\"axaAzureLoginUPN\", \"company\"})\nin\n  #\"Removed other columns\";\r\nshared DestinationForWriteToDatabaseTableFrom_AD_users = let\r\n  Pattern = Lakehouse.Contents([]),\r\n  Navigation_1 = Pattern{[workspaceId = \"c724be80-d86a-4027-a5e0-facd68b67834\"]}[Data],\r\n  Navigation_2 = Navigation_1{[lakehouseId = \"c1c439bf-5c3d-4ad4-89a8-2fe31902d3c5\"]}[Data],\r\n  TableNavigation = Navigation_2{[Id = \"AD_users\", ItemKind = \"Table\"]}?[Data]?,\r\n  Table = NavigationTable.CreateTableOnDemand(TableNavigation, #table(type table[axaAzureLoginUPN = nullable text, company = nullable text], {}), [DeleteWhenEmpty = true])\r\nin\r\n  Table;\r\n[Staging = \"DefaultStaging\"]\r\nshared WriteToDatabaseTableFrom_TransformForOutputToDatabaseTableFrom_AD_users = let\r\n  WriteToDatabaseTableFrom_TransformForOutputToDatabaseTableFrom_AD_users = Pipeline.ExecuteAction(ValueAction.WithTransaction([Target = DestinationForWriteToDatabaseTableFrom_AD_users], (txn) => {TableAction.DeleteRows(txn[Target]), TableAction.InsertRows(txn[Target], TransformForOutputToDatabaseTableFrom_AD_users), Action.DoNothing}))\r\nin\r\n  WriteToDatabaseTableFrom_TransformForOutputToDatabaseTableFrom_AD_users;\r\nshared TransformForOutputToDatabaseTableFrom_AD_users = let\r\n    SourceTable = Table.SelectColumns(AD_users, {\"axaAzureLoginUPN\", \"company\"})\r\nin\r\n    SourceTable;\r\n","connectionOverrides":[{"path":"https://pbimlo-my.sharepoint.com/personal/o_manel_pbimlo_onmicrosoft_com","kind":"SharePoint","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"SharePoint\",\"path\":\"https://pbimlo-my.sharepoint.com/personal/o_manel_pbimlo_onmicrosoft_com\"}","audience":null},{"path":"Lakehouse","kind":"Lakehouse","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"Lakehouse\",\"path\":\"Lakehouse\"}","audience":null}]},"entities":[{"$type":"LocalEntity","name":"Workspace_users","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Workspace_users.parquet"},"annotations":[{"name":"ppdf:entityKeys","value":"[]"}],"attributes":[{"name":"Workspace","dataType":"string"},{"name":"WorkspaceID","dataType":"string"},{"name":"UserPrincipalName","dataType":"string"},{"name":"AccessRights","dataType":"string"},{"name":"CompanyName","dataType":"string"}]},{"$type":"LocalEntity","name":"Company_Mapping","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Company_Mapping.parquet"},"annotations":[{"name":"ppdf:entityKeys","value":"[]"}],"attributes":[{"name":"Company","dataType":"string"},{"name":"OpCo","dataType":"string"},{"name":"UserLegalEntityCode","dataType":"string"}]},{"$type":"LocalEntity","name":"AD_users","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"AD_users.parquet"},"annotations":[{"name":"ppdf:entityKeys","value":"[]"}],"attributes":[{"name":"axaAzureLoginUPN","dataType":"string"},{"name":"company","dataType":"string"}]}]}